export const holidays = [
    { date: "1 Jan", day: "Friday", Name: "New Year's Day", type: "Restricted Holiday" },
    { date: "13 Jan", day: "Wednesday", Name: "Lohri", type: "Restricted Holiday" },
    { date: "14 Jan", day: "Thursday", Name: "Pongal", type: "Restricted Holiday" },
    { date: "14 Jan", day: "Thursday", Name: "Makar Sankranti", type: "Restricted Holiday" },
    { date: "20 Jan", day: "Wednesday", Name: "Guru Govind Singh Jayanti", type: "Restricted Holiday" },
    { date: "26 Jan", day: "Tuesday", Name: "Republic Day", type: "Gazetted Holiday" },
    { date: "12 Feb", day: "Friday", Name: "Chinese New Year", type: "Observance" },
    { date: "14 Feb", day: "Sunday", Name: "Valentine's Day", type: "Observance" },
    { date: "16 Feb", day: "Tuesday", Name: "Vasant Panchami", type: "Restricted Holiday" },
    { date: "19 Feb", day: "Friday", Name: "Shivaji Jayanti", type: "Restricted Holiday" },
    { date: "26 Feb", day: "Friday", Name: "Hazarat Ali's Birthday", type: "Restricted Holiday" },
    { date: "27 Feb", day: "Saturday", Name: "Guru Ravidas Jayanti", type: "Restricted Holiday" },
    { date: "8 Mar", day: "Monday", Name: "Maharishi Dayanand Saraswati Jayanti", type: "Restricted Holiday" },
    { date: "11 Mar", day: "Thursday", Name: "Maha Shivaratri/Shivaratri", type: "Gazetted Holiday" },
    { date: "20 Mar", day: "Saturday", Name: "March Equinox", type: "Season" },
    { date: "28 Mar", day: "Sunday", Name: "First day of Passover", type: "Observance" },
    { date: "28 Mar", day: "Sunday", Name: "Holika Dahana", type: "Restricted Holiday" },
    { date: "29 Mar", day: "Monday", Name: "Holi", type: "Gazetted Holiday" },
    { date: "1 Apr", day: "Thursday", Name: "Maundy Thursday", type: "Observance, Christian" },
    { date: "2 Apr", day: "Friday", Name: "Good Friday", type: "Gazetted  Holiday" },
    { date: "4 Apr", day: "Sunday", Name: "Easter Day", type: "Restricted Holiday" },
    { date: "13 Apr", day: "Tuesday", Name: "Chaitra Sukhladi", type: "Restricted Holiday" },
    { date: "14 Apr", day: "Wednesday", Name: "Vaisakhi", type: "Restricted Holiday" },
    { date: "14 Apr", day: "Wednesday", Name: "Mesadi", type: "Restricted Holiday" },
    { date: "14 Apr", day: "Wednesday", Name: "Ambedkar Jayanti", type: "Observance" },
    { date: "15 Apr", day: "Thursday", Name: "Bahag Bihu/Vaisakhadi", type: "Restricted Holiday" },
    { date: "21 Apr", day: "Wednesday", Name: "Rama Navami", type: "Restricted Holiday" },
    { date: "25 Apr", day: "Sunday", Name: "Mahavir Jayanti", type: "Restricted Holiday" },

    { date: "1 May", day: "Saturday", Name: "May Day", type: "Observance" },
    { date: "7 May", day: "Friday", Name: "Jamat Ul-Vida", type: "Restricted Holiday" },
    { date: "9 May", day: "Sunday", Name: "Mother's Day", type: "Observance" },
    { date: "9 May", day: "Sunday", Name: "Birthday of Ravindranath", type: "Restricted Holiday" },
    { date: "14 May", day: "Friday", Name: "Ramzan Id/Eid-ul-Fitar", type: "Gazetted Holiday" },
    { date: "14 May", day: "Friday", Name: "Ramzan Id/Eid-ul-Fitar", type: "Muslim, Common local holiday" },

    { date: "20 Jun", day: "Sunday", Name: "Father's Day", type: "Observance" },
    { date: "21 Jun", day: "Monday", Name: "June Solstice", type: "Season" },

    { date: "12 Jul", day: "Monday", Name: "Rath Yatra", type: "Gazetted Holiday" },
    { date: "21 Jul", day: "Wednesday", Name: "Bakr Id/Eid ul-Adha", type: "Gazetted  Holiday" },
    { date: "24 Jul", day: "Saturday", Name: "Guru Purnima", type: "Observance" },

    //aug remaining
    { date: "26 Jun", day: "Wednesday", Name: "	Buddha Purnima/Vesak", type: "Gazetted Holiday" },
    { date: "26 Jun", day: "Wednesday", Name: "	Buddha Purnima/Vesak", type: "Gazetted Holiday" },
    { date: "26 Jun", day: "Wednesday", Name: "	Buddha Purnima/Vesak", type: "Gazetted Holiday" },
    { date: "26 Jun", day: "Wednesday", Name: "	Buddha Purnima/Vesak", type: "Gazetted Holiday" },
    { date: "26 Jun", day: "Wednesday", Name: "	Buddha Purnima/Vesak", type: "Gazetted Holiday" },
    { date: "26 Jun", day: "Wednesday", Name: "	Buddha Purnima/Vesak", type: "Gazetted Holiday" },
]